FROM debian:stretch

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates

ENV PROJECT_ROOT=.
ENV K8S=$PROJECT_ROOT/k8s
ENV HELM_CHARTS=$PROJECT_ROOT/charts

RUN apt-get update && apt-get install -y curl
RUN curl -O https://get.helm.sh/helm-v2.14.2-linux-amd64.tar.gz
RUN tar -xvf helm-v2.14.2-linux-amd64.tar.gz
RUN mv linux-amd64/helm /usr/local/bin/helm

# PORTER_MIXINS

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.


# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR
